language: go

matrix:
  include:
    - os: linux
      go: "1.11.x"
    - os: osx
      go: "1.11.x"
    - os: windows
      go: "1.11.x"

before_install:
  - go get -v -u github.com/dvyukov/go-fuzz/...
  
script:
  - go test -v ./... -short
  - go test -v ./...
