language: go

matrix:
  include:
    - os: osx
      go: "1.11.x"
    - os: windows
      go: "1.11.x"
    - os: linux
      go: "1.11.x"
    - os: linux
      go: "1.10.x"
    - os: linux
      go: "1.9.x"

script:
  - go test ./...
